# Generated by Django 5.0.7 on 2024-07-27 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
    ]
