# Generated by Django 5.0.7 on 2024-07-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_cashback"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceUsageStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_statistics",
                        to="blog.service",
                    ),
                ),
            ],
        ),
    ]
