# Generated by Django 5.0.7 on 2024-08-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("blog", "0014_averagerating_chatmessage_offer_progresstracker_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google Analytics"), ("matomo", "Matomo")],
                        max_length=50,
                    ),
                ),
                ("tracking_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="PWAConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=50)),
                ("start_url", models.CharField(max_length=255)),
                ("background_color", models.CharField(max_length=7)),
                ("theme_color", models.CharField(max_length=7)),
                (
                    "display",
                    models.CharField(
                        choices=[
                            ("standalone", "Standalone"),
                            ("fullscreen", "Fullscreen"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SEOConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("keywords", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="content_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bonuspoint",
            name="reason_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bonuspoint",
            name="reason_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status_en",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="status_uz",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cashback",
            name="description_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cashback",
            name="description_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status_en",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status_uz",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="comment_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="supportresponse",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="supportresponse",
            name="message_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category_en",
            field=models.CharField(
                choices=[("service", "Service"), ("restaurant", "Restaurant")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="category_uz",
            field=models.CharField(
                choices=[("service", "Service"), ("restaurant", "Restaurant")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="status_en",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="status_uz",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="subject_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="subject_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="image_en",
            field=models.ImageField(blank=True, null=True, upload_to="tables/"),
        ),
        migrations.AddField(
            model_name="table",
            name="image_uz",
            field=models.ImageField(blank=True, null=True, upload_to="tables/"),
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=20
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="blog.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_uz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="blog.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="blog.paymentmethod",
            ),
        ),
        migrations.CreateModel(
            name="ProductLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewIncentive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus_points", models.IntegerField(default=0)),
                ("discount_given", models.BooleanField(default=False)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.review"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
